# Generated by Django 3.0.1 on 2020-05-07 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='custinfo',
            new_name='customer',
        ),
    ]
