# Generated by Django 3.0.1 on 2020-05-21 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20200517_1843'),
    ]

    operations = [
        migrations.DeleteModel(
            name='menu',
        ),
    ]
