# Generated by Django 3.0.1 on 2020-06-07 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_id', models.CharField(max_length=100, null=True)),
                ('sub_type', models.CharField(choices=[('OneOff', 'OneOff'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Monthly', max_length=100, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.Client')),
            ],
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.Subscription'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='sub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.Subscription'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sub_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.Subscription'),
        ),
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
