# Generated by Django 3.0.1 on 2020-05-21 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20200521_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='items',
            field=models.CharField(choices=[('Rice', 'Rice'), ('Beans', 'Beans'), ('Sauces', 'Sauces')], default='Monthly', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='order_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.Order'),
        ),
    ]
