# Generated by Django 3.0.1 on 2020-05-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20200521_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='items',
            field=models.CharField(choices=[('Rice', 'Rice'), ('Beans', 'Beans'), ('Sauces', 'Sauces')], max_length=100, null=True),
        ),
    ]
